In [1]:
import numpy as np

#### 1. create a numpy array of 5 zeros.
    -check datatype, itemsize and shape of above

In [7]:
arr  = np.zeros(5)
print(arr.dtype)
print(arr.shape)
print(type(arr))
print(arr)
print(arr.itemsize)


float64
(5,)
<class 'numpy.ndarray'>
[0. 0. 0. 0. 0.]
8


#### 2. create a numpy array of ones of shape (5,4)

In [10]:
arr1 = np.ones((5,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 3. create a matrix of shape 4,5 with numbers from 1-20

In [11]:
arr = np.arange(1,21)
arr.resize(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#### 4. multiply all elements of above array by 10

In [12]:
arr*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

#### 5. print odd elements from array

In [13]:
arr[np.where(arr%2)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### 6.replace all even elements by their negative

In [18]:
arr[np.where(arr%2==0)] = -arr[np.where(arr%2==0)]
print(arr)

[[ -1   1  -3   3  -5]
 [  5  -7   7  -9   9]
 [-11  11 -13  13 -15]
 [ 15 -17  17 -19  19]]


#### 7.create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

In [21]:
M1 = np.linspace(1,16,16)
M1.resize(4,4)
M1 = np.matrix(M1)
print(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


#### 8.create a transpose of above matrix call it M2

In [23]:
M2 = np.transpose(M1)
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


#### 9.find sum of above matrix M3 = (M1 + M2)

In [24]:
M3 = M1 + M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


#### 10.Find Transpose of M3, Call it MT1. Check if M3 == MT1

In [27]:
MT1 = np.transpose(M3)
print((M3 == MT1).all())

True


#### 11.find diffrence of M4 = (M1 - M2)

In [28]:
M4 = M1 - M2
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


#### 12.Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

In [31]:
MT2 = np.transpose(M4)
print((M4 == MT2).all())
print((M4 == -MT2).all())

False
True


#### 13.create a matrix (3x4) R1 of random numbers between 10-40

In [34]:
R1 = np.random.randint(10,40,12)
R1.resize(3,4)
R1 = np.matrix(R1)
print(R1)

[[21 22 16 24]
 [21 26 29 20]
 [30 19 18 25]]


#### 14. find min and max column wise

In [35]:
print("min", np.min(R1, axis=0))
print("max", np.max(R1, axis=0))

min [[21 19 16 20]]
max [[30 26 29 25]]


#### 15.replace the last column with sum of all the columns

In [36]:
R1[:,3] = np.sum(R1,axis=1)
print(R1)

[[21 22 16 83]
 [21 26 29 96]
 [30 19 18 92]]


#### 16.create a matrix (3x4) R1 of random numbers between 10-40

In [40]:
R1 = np.random.randint(10,40,12)
R1.resize(3,4)
R1 = np.matrix(R1, dtype=float)
print(R1)

[[22. 26. 13. 36.]
 [16. 21. 34. 32.]
 [16. 35. 37. 32.]]


#### 17.replace all even elements with nan in R1

In [41]:
R1[np.where(R1%2==0)] = np.nan
print(R1)

[[nan nan 13. nan]
 [nan 21. nan nan]
 [nan 35. 37. nan]]


#### 18.count number of nan in R1

In [42]:
np.isnan(R1).sum()

8

#### 19.check output of this code

In [52]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
