In [1]:
import numpy as np

In [4]:
# 1. create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above
arr = np.zeros(5)
print(arr.shape)
print(type(arr))
print(arr)
print(arr.itemsize)
print(arr.dtype)

(5,)
<class 'numpy.ndarray'>
[0. 0. 0. 0. 0.]
8
float64


In [6]:
# 2. create a numpy array of ones of shape (5,4)
arr1 = np.ones((5,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# 3. create a matrix of shape 4,5 with numbers from 1-20
arr = np.arange(1,21)
arr.resize(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [11]:
# 4. multiply all elements of above array by 10
arr*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [12]:
# 5. print odd elements from array
arr[np.where(arr%2)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
# 6.replace all even elements by their negative
arr[np.where(arr%2==0)] = -arr[np.where(arr%2==0)]
print(arr)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [21]:
# 7.create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1 = np.linspace(1,16,16)
M1.resize(4,4)
M1 = np.matrix(M1)
print(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [23]:
# 8.create a transpose of above matrix call it M2
M2 = np.transpose(M1)
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [24]:
# 9.find sum of above matrix M3 = (M1 + M2)
M3 = M1 + M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [35]:
# 10.Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = np.transpose(M3)
print((M3 == MT1).all())

True


In [37]:
# 11.find diffrence of M4 = (M1 - M2)
M4 = (M1 - M2)
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [40]:
# 12.Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = np.transpose(M4)
print((M4 == MT2).all())
print((M4 == -MT2).all())

False
True


In [2]:
# 13.create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12)
R1.resize(3,4)
R1 = np.matrix(R1)
print(R1)

[[29 13 13 24]
 [12 11 27 20]
 [32 30 22 13]]


In [3]:
# 14.find min and max column wise
print("min", np.min(R1, axis=0))
print("max", np.max(R1, axis=0))

min [[12 11 13 13]]
max [[32 30 27 24]]


In [4]:
# 15.replace the last column with sum of all the columns
R1[:,3] = np.sum(R1, axis=1)
print(R1)

[[29 13 13 79]
 [12 11 27 70]
 [32 30 22 97]]


In [81]:
# 16.create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12)
R1.resize(3,4)
R1 = np.matrix(R1, dtype=float)
print(R1)


[[24. 28. 13. 19.]
 [36. 14. 22. 36.]
 [20. 38. 22. 22.]]


In [82]:
# 17.replace all even elements with nan in R1
R1[np.where(R1%2==0)] = np.nan
print(R1)

[[nan nan 13. 19.]
 [nan nan nan nan]
 [nan nan nan nan]]


In [90]:
# 18.count number of nan in R1
np.isnan(R1).sum()

10

In [91]:
# 19.check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [17]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '