In [2]:
import numpy as np

In [11]:
a = np.array([1,2,3])
print(a)
print(a.max())
print(max(a))

[1 2 3]
3
3


In [15]:
a = np.array([1,2,3])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[1 2 3]
1
3
(3,)


In [36]:
a = np.array(range(10), dtype = np.float32)
a = a.reshape(2,5)
print(a)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.dtype)
print(a.max(axis = 0))
print(a.max(axis = 1))
print(a.mean())
print(a.mean(axis = 0))
print(a.sum())

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
2
10
(2, 5)
4
float32
[5. 6. 7. 8. 9.]
[4. 9.]
4.5
[2.5 3.5 4.5 5.5 6.5]
45.0


In [42]:
a = np.array(["a", "bcd", "pq"])
print(a)
print(a.dtype)
print(a.itemsize)

# 0000 0001 1000 1111
# 90 0000 0001
# 91 1000 1111

# 90 1000 1111
# 91 0000 0001

['a' 'bcd' 'pq']
<U3
12


In [63]:
print(dir(np.random))
print(np.random.randn(10)) # normal distribution
print(np.random.randn(3,4))
print(np.random.randint(10)) # randrange
print(np.random.randint(10,20,2))
print(np.random.randint(10,20,(2,3)))

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']
[ 0.89116493  0.77346469 -0.38867897  0.29391932  0.24701653  0.00277297
  0.799137

In [68]:
arr = np.random.randint(1,10,(3,4))
print(arr)
np.random.shuffle(arr)
print(arr)

[[8 7 3 9]
 [9 8 1 2]
 [8 4 2 9]]
[[8 4 2 9]
 [9 8 1 2]
 [8 7 3 9]]


In [83]:
print(np.ones(10, dtype = np.int8))
print(np.zeros(10, dtype = np.int8))
print(np.arange(10, dtype = np.int8))
print(np.arange(10,20, dtype = np.int8))
print(np.arange(10,20,2, dtype = np.int8))
print(np.eye(4))
print(np.linspace(10,20, 5, dtype=np.int16))

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[10 12 15 17 20]


In [92]:
a = np.arange(1,13)
print(a)
a = a.reshape(3,4)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [90]:
a = np.arange(1,13)
print(a)
a.resize(4,5)
print(a)
a.resize(3,3)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  0  0  0]
 [ 0  0  0  0  0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
a = np.arange(1,13).reshape(3,4)
print(a)
print(a*10)
print(a+10)
print(a*a)
print(a %2 == 0)
b =  np.arange(10,14)
print(b)
print(a*b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[10 11 12 13]
[[ 10  22  36  52]
 [ 50  66  84 104]
 [ 90 110 132 156]]


In [115]:
a = np.arange(1,13).reshape(3,4)
print(a)
print(a %2 == 0)
r  =  a%2==0
print(a[r])
print(a[(a>4) & (a <10)])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[ 2  4  6  8 10 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [132]:
a  = np.array([1,2,np.nan])
print(a)
print(a.sum())
print(a.mean())
print(a == np.nan) # this doesn't work
print(np.isnan(a)) # this works: use this
print(np.any(a))
print(np.all(a))
r=  np.any(a)
print(type(r))

a = np.array([10,11,12,13], dtype = "int16")
print()
print(a)
r = a%2 == 0
print(r, r.any(), r.all())
r = a%20 == 0
print(r, r.any(), r.all())
r = (a>1)
print(r, r.any(), r.all())

[ 1.  2. nan]
nan
nan
[False False False]
[False False  True]
True
True
<class 'numpy.bool_'>

[10 11 12 13]
[ True False  True False] True False
[False False False False] False False
[ True  True  True  True] True True


In [145]:
a1 = np.arange(10)
print(a1, a1.dtype)
a2 = np.linspace(10,20,10)
print(a2, a2.dtype)
a2 += a1
print(a1)
print(a2)

[0 1 2 3 4 5 6 7 8 9] int32
[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ] float64
[0 1 2 3 4 5 6 7 8 9]
[10.         12.11111111 14.22222222 16.33333333 18.44444444 20.55555556
 22.66666667 24.77777778 26.88888889 29.        ]


In [153]:
a  = np.arange(10,22).reshape(3,4)
print(a)
print()
print(a[1])
print(a[:,1])
print(a[1,1])
print()
print(a[1:,1])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[14 15 16 17]
[11 15 19]
15

[15 19]


In [156]:
a  = np.arange(10,22).reshape(3,4)
print(a)
print()
print(a[1:,1])
print()
print(a[1:,::2])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[15 19]

[[14 16]
 [18 20]]


In [158]:
a  = np.arange(10,40).reshape(5,6)
print(a)
print()
print(a[1:4,1])

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]

[17 23 29]


In [159]:
a  = np.arange(10,40).reshape(5,6)

for row in a:
    print(row)

[10 11 12 13 14 15]
[16 17 18 19 20 21]
[22 23 24 25 26 27]
[28 29 30 31 32 33]
[34 35 36 37 38 39]


In [172]:
a  = np.arange(10,40).reshape(5,6)
print(a)
print()
print(a > 30)
print()
r = np.where(a > 30)
print(r)
print()
print(a[r])

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True  True  True]
 [ True  True  True  True  True  True]]

(array([3, 3, 3, 4, 4, 4, 4, 4, 4], dtype=int64), array([3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))

[31 32 33 34 35 36 37 38 39]


In [171]:
a  = np.arange(10,40).reshape(5,6)
print(a)
print()
print(a[(1,3),]) # get elements at particular rows
print(a[:,(1,3)]) # get elements at particular rows
print(a[(1,3),(0,2)]) # Get element at (r,c)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]

[[16 17 18 19 20 21]
 [28 29 30 31 32 33]]
[[11 13]
 [17 19]
 [23 25]
 [29 31]
 [35 37]]
[16 30]
