# Pandas
- Series : 1-d
- Dataframe:  2-d
- Columns: attributes, features
- Rows: Records, entries, data points, samples


In [9]:
import pandas as pd

In [5]:
print(dir(pd))


['Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseArray', 'SparseDataFrame', 'SparseDtype', 'SparseSeries', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_lib', '_libs', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_rang

In [7]:
print(dir(pd.Series))

['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__

In [8]:
print(dir(pd.DataFrame))

['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__

In [12]:
s = pd.Series([10,20], dtype = "int8")
print(s)

0    10
1    20
dtype: int8


In [5]:
import numpy as np
mat = np.random.randint(10,20,20).reshape(4,5)
print(mat)
print(mat > 15)
np.where(mat > 15)

np.where(~(mat > 15))

[[19 18 18 19 18]
 [19 10 15 17 15]
 [16 12 12 14 17]
 [14 12 11 15 12]]
[[ True  True  True  True  True]
 [ True False False  True False]
 [ True False False False  True]
 [False False False False False]]


(array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([1, 2, 4, 1, 2, 3, 0, 1, 2, 3, 4], dtype=int64))

In [8]:
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [18]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [23]:
mat =  np.random.randint(1,100, 20).reshape(4,5)
df = pd.DataFrame(mat, columns = list('abcde'), index = ["ab", 'cd','p','q'])
print(df)

     a   b   c   d   e
ab  89  69  94  25  11
cd  18  28  24   5  72
p   71  34  24  36  35
q   78  27  80  61  26


In [15]:
df.describe()

a          b          c         d          e
count   4.000000   4.000000   4.000000   4.00000   4.000000
mean   75.500000  33.750000  49.250000  73.75000  55.750000
std    23.923489  20.072784  43.176961  23.97742  30.630867
min    42.000000   9.000000   9.000000  40.00000  31.000000
25%    67.500000  26.250000  13.500000  65.50000  31.000000
50%    81.500000  34.000000  49.000000  80.50000  49.000000
75%    89.500000  41.500000  84.750000  88.75000  73.750000
max    97.000000  58.000000  90.000000  94.00000  94.000000

In [53]:
df1 = pd.DataFrame([list('abcd'), [1,2,3,4]])
print(df1)
print(df1.describe())

   0  1  2  3
0  a  b  c  d
1  1  2  3  4
        0  1  2  3
count   2  2  2  2
unique  2  2  2  2
top     1  2  c  d
freq    1  1  1  1


In [55]:
mat =  np.random.randint(1,100, 40).reshape(10,4)
df = pd.DataFrame(mat, columns = list('abcd'))
print(df)

    a   b   c   d
0   9  11  85  49
1  60  30  80  41
2  40  64  77  47
3  15  91  25  55
4  75  12  52  87
5  21   9   1  90
6  16  82  27  99
7  86  43  72  87
8  91  48  48  87
9  52  27  72  16


In [30]:
print(df.mean())
print(df.max())

a    67.3
b    42.5
c    47.3
d    69.7
dtype: float64
a    99
b    87
c    89
d    95
dtype: int32


In [33]:
print(df.head())
print(df.head(2))
print(df.tail(5))
print(df.tail(3))

    a   b   c   d
0  99  21  89  29
1  61  53  88  92
2  87  25  16  54
3  20  75  56  61
4  37   6  17  86
    a   b   c   d
0  99  21  89  29
1  61  53  88  92
    a   b   c   d
5  61  87  53  67
6  97  50  30  68
7  76  29  87  51
8  93  40  24  94
9  42  39  13  95
    a   b   c   d
7  76  29  87  51
8  93  40  24  94
9  42  39  13  95


In [37]:
print(df.columns) # columns
print(df.dtypes)
print(df.index) # rows
print(df.shape)
print(df.size)

Index(['a', 'b', 'c', 'd'], dtype='object')
a    int32
b    int32
c    int32
d    int32
dtype: object
RangeIndex(start=0, stop=10, step=1)
(10, 4)
40


In [38]:
df

a   b   c   d
0  99  21  89  29
1  61  53  88  92
2  87  25  16  54
3  20  75  56  61
4  37   6  17  86
5  61  87  53  67
6  97  50  30  68
7  76  29  87  51
8  93  40  24  94
9  42  39  13  95

In [47]:
res = df < 10
print(res)
print(res.sum())
print(res.any())
print(res.all())

       a      b      c      d
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False   True  False  False
5  False  False  False  False
6  False  False  False  False
7  False  False  False  False
8  False  False  False  False
9  False  False  False  False
a    0
b    1
c    0
d    0
dtype: int64
a    False
b     True
c    False
d    False
dtype: bool
a    False
b    False
c    False
d    False
dtype: bool


In [48]:
res = df > 10
print(res)
print(res.sum())
print(res.any())
print(res.all())

      a      b     c     d
0  True   True  True  True
1  True   True  True  True
2  True   True  True  True
3  True   True  True  True
4  True  False  True  True
5  True   True  True  True
6  True   True  True  True
7  True   True  True  True
8  True   True  True  True
9  True   True  True  True
a    10
b     9
c    10
d    10
dtype: int64
a    True
b    True
c    True
d    True
dtype: bool
a     True
b    False
c     True
d     True
dtype: bool


In [49]:
print(df)

    a   b   c   d
0  99  21  89  29
1  61  53  88  92
2  87  25  16  54
3  20  75  56  61
4  37   6  17  86
5  61  87  53  67
6  97  50  30  68
7  76  29  87  51
8  93  40  24  94
9  42  39  13  95


In [50]:
res  =  df.drop(columns=['a'])
print(res)
print(df)

    b   c   d
0  21  89  29
1  53  88  92
2  25  16  54
3  75  56  61
4   6  17  86
5  87  53  67
6  50  30  68
7  29  87  51
8  40  24  94
9  39  13  95
    a   b   c   d
0  99  21  89  29
1  61  53  88  92
2  87  25  16  54
3  20  75  56  61
4  37   6  17  86
5  61  87  53  67
6  97  50  30  68
7  76  29  87  51
8  93  40  24  94
9  42  39  13  95


In [56]:
res  =  df.drop(columns=['a'], inplace = True)
print(res)
print(df)

None
    b   c   d
0  11  85  49
1  30  80  41
2  64  77  47
3  91  25  55
4  12  52  87
5   9   1  90
6  82  27  99
7  43  72  87
8  48  48  87
9  27  72  16


In [57]:
res  =  df.drop(index=[2,5])
print(res)
print(df)

    b   c   d
0  11  85  49
1  30  80  41
3  91  25  55
4  12  52  87
6  82  27  99
7  43  72  87
8  48  48  87
9  27  72  16
    b   c   d
0  11  85  49
1  30  80  41
2  64  77  47
3  91  25  55
4  12  52  87
5   9   1  90
6  82  27  99
7  43  72  87
8  48  48  87
9  27  72  16


In [63]:
print(df.b)
print()
print(df['c']) # single index means column names

0    11
1    30
2    64
3    91
4    12
5     9
6    82
7    43
8    48
9    27
Name: b, dtype: int32
0    85
1    80
2    77
3    25
4    52
5     1
6    27
7    72
8    48
9    72
Name: c, dtype: int32


In [71]:
# loc
# by default goes for rows
# uses names not index values 
print( df.loc[0, 'b'] ) # take row 0 and column 'b'
print( df.loc[0:4])
print()
print( df.loc[0:4, ('b','d') ]) # rows from 0-4 and columns 'b' and 'd'
print()
print( df.loc[:, ('b','d') ])
print()
print( df.loc[:, :'b' ])
print()
print( df.loc[:, 'b': ])

11
    b   c   d
0  11  85  49
1  30  80  41
2  64  77  47
3  91  25  55
4  12  52  87

    b   d
0  11  49
1  30  41
2  64  47
3  91  55
4  12  87

    b   d
0  11  49
1  30  41
2  64  47
3  91  55
4  12  87
5   9  90
6  82  99
7  43  87
8  48  87
9  27  16

    b
0  11
1  30
2  64
3  91
4  12
5   9
6  82
7  43
8  48
9  27

    b   c   d
0  11  85  49
1  30  80  41
2  64  77  47
3  91  25  55
4  12  52  87
5   9   1  90
6  82  27  99
7  43  72  87
8  48  48  87
9  27  72  16


In [73]:
# iloc 
# iloc always uses indexs
print(df.iloc[0:4, 0])


0    11
1    30
2    64
3    91
Name: b, dtype: int32
