## NUMPY

In [1]:
#1.create a numpy array of 5 zeros.check datatype, itemsize and shape of above
import numpy as np
a = np.zeros(5)
print(a.shape)
print(type(a))
print(a)
print(a.itemsize)
print(a.dtype)

(5,)
<class 'numpy.ndarray'>
[0. 0. 0. 0. 0.]
8
float64


In [2]:
# 2.create a numpy array of ones of shape (5,4)
ar = np.ones((5,4))
print(ar)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# 3. create a matrix of shape 4,5 with numbers from 1-20
a = np.arange(1,21)
a.resize(4,5)
print("The matrix:", end="\n")
print(a)

The matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
# 4. multiply all elements of above array by 10
a*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [7]:
# 5. print odd elements from array
a[np.where(a%2!=0)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
# 6.Replace all even elements by their negative
a[np.where(a%2==0)] = -a[np.where(a%2==0)]
print(a)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [13]:
# 7.Create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1 = np.linspace(1,16,16)
M1.resize(4,4)
M1 = np.matrix(M1)
print(M1)
type(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


numpy.matrix

In [14]:
# 8.Create a transpose of above matrix call it M2
M2 = np.transpose(M1)
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [15]:
#9.Find sum of above matrix M3 = (M1 + M2)
M3 = M1 + M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [17]:
#10.Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = np.transpose(M3)
print((M3 == MT1).all())
type(M3)

True


numpy.matrix

In [18]:
#11.Find diffrence of M4 = (M1 - M2)
M4 = (M1 - M2)
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [19]:
#12.Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = np.transpose(M4)
print((M4 == MT2).all())
print((M4 == -MT2).all())

False
True


In [31]:
#13.Create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12)
R1.resize(3,4)
R1 = np.matrix(R1)
print(R1)

print()

# 14.Find min and max column wise
print("min", np.min(R1, axis=0))
print("max", np.max(R1, axis=0))

print()

# 15.Replace the last column with sum of all the columns
R1[:,3] = np.sum(R1, axis=1)
print(R1)


[[37 10 32 29]
 [25 31 10 15]
 [17 20 22 29]]

min [[17 10 10 15]]
max [[37 31 32 29]]

[[ 37  10  32 108]
 [ 25  31  10  81]
 [ 17  20  22  88]]


In [46]:
# 16.Create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12)
R1.resize(3,4)
R1 = np.matrix(R1)
R1 = np.matrix(R1, dtype=float)
print(R1)


print()
# 17.Replace all even elements with nan in R1
R1[np.where(R1%2==0)] = np.nan
print(R1)


print()

#18.Count number of nan in R1
np.isnan(R1).sum()


[[20. 14. 25. 14.]
 [16. 20. 22. 21.]
 [11. 14. 25. 33.]]

[[nan nan 25. nan]
 [nan nan nan 21.]
 [11. nan 25. 33.]]



7

In [50]:
#19.Check output of this code
a1 = np.arange(1,10).reshape(3,3)
print(a1)
print()
a2 = np.arange(11,20).reshape(3,3)
print(a2)
print()
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
